[features]
seeds = false
[registry]
url = "https://anchor.projectserum.com"

[programs.localnet]
faucet = "pNZo25EcxWvfwPXVVnzPaszBsFNpit1N7ErAcL7w8Bw"
[programs.devnet]
faucet = "pNZo25EcxWvfwPXVVnzPaszBsFNpit1N7ErAcL7w8Bw"
[programs.mainnet]
faucet = "pNZo25EcxWvfwPXVVnzPaszBsFNpit1N7ErAcL7w8Bw"
[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "/home/linxueyuan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000